# Generated by Django 4.0.6 on 2022-07-08 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_newuser_options_alter_newuser_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='user_name',
            new_name='username',
        ),
    ]
