# Generated by Django 4.0.6 on 2022-09-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_newuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
