# Generated by Django 4.0.6 on 2022-09-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_newuser_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='newuser',
            name='living_place',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='newuser',
            name='phone',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='newuser',
            name='ware_house',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
