# Generated by Django 3.2.8 on 2021-10-25 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenDiagonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='diagonal')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_number', models.IntegerField(verbose_name='frequency')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='type')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(max_length=255, verbose_name='camera')),
                ('diagonal_screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.screendiagonal', verbose_name='ScreenDiagonal')),
                ('screen_frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.screenfrequency', verbose_name='ScreenFrequency')),
                ('screen_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.screentype', verbose_name='ScreenType')),
            ],
        ),
    ]
