# Generated by Django 3.2.8 on 2021-10-25 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_gigabite', models.IntegerField()),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='MemorySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_slots', models.IntegerField()),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='memory_type')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='OperationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='operation_system')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='processoetype')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.AddField(
            model_name='screentype',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='RandomAccessMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.memorycapacity', verbose_name='MemoryCapacity')),
                ('memory_slots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.memoryslot', verbose_name='MemorySlot')),
                ('memory_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.memorytype', verbose_name='NemoryType')),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.processortype', verbose_name='ProcessorType')),
                ('operation_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristics.operationsystem', verbose_name='OperationSystem')),
            ],
        ),
    ]
