# Generated by Django 3.2.8 on 2021-10-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0003_battery_colorcorp_corp_datastoragedevices_videocard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_adapters', models.CharField(max_length=255)),
                ('wireless_connection', models.CharField(max_length=255)),
                ('input_output', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CountryBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='country_brand__flags/Data%y/%m/%d/')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='CountryMade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='country_made_flags/Data%y/%m/%d/')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/Data%y/%m/%d/')),
            ],
        ),
    ]
