# Generated by Django 3.2.8 on 2021-10-26 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0004_connection_countrybrand_countrymade_producttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCardMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_card_capacity', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.AlterField(
            model_name='memorycapacity',
            name='number_of_gigabite',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='videocard',
            name='videocard_memory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.videocardmemory', verbose_name='VideoCardMemory'),
        ),
    ]
