# Generated by Django 3.2.8 on 2021-10-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20211026_1731'),
        ('characteristics', '0005_auto_20211026_0900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
        migrations.RemoveField(
            model_name='corp',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='corp',
            name='color',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='diagonal_screen',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='screen_frequency',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='screen_type',
        ),
        migrations.RemoveField(
            model_name='videocard',
            name='videocard_memory',
        ),
        migrations.AddField(
            model_name='processortype',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Battery',
        ),
        migrations.DeleteModel(
            name='ColorCorp',
        ),
        migrations.DeleteModel(
            name='Corp',
        ),
        migrations.DeleteModel(
            name='Screen',
        ),
    ]
