# Generated by Django 3.2.8 on 2021-10-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0006_auto_20211026_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomaccessmemory',
            name='memory_capacity',
        ),
        migrations.RemoveField(
            model_name='randomaccessmemory',
            name='memory_slots',
        ),
        migrations.RemoveField(
            model_name='randomaccessmemory',
            name='memory_type',
        ),
        migrations.AlterField(
            model_name='screenfrequency',
            name='frequency_number',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Processor',
        ),
        migrations.DeleteModel(
            name='RandomAccessMemory',
        ),
    ]
