# Generated by Django 3.2.8 on 2021-10-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0008_auto_20211026_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrybrand',
            options={'ordering': ['name'], 'verbose_name': 'Country Brand', 'verbose_name_plural': 'Countries Brand'},
        ),
        migrations.AlterModelOptions(
            name='countrymade',
            options={'ordering': ['name'], 'verbose_name': 'Country Made', 'verbose_name_plural': 'Countries Made'},
        ),
        migrations.AlterModelOptions(
            name='datastoragedevices',
            options={'ordering': ['hard_drive_capacity', 'hard_drive_type'], 'verbose_name': 'Storage Device', 'verbose_name_plural': 'Storage Devices'},
        ),
        migrations.AlterModelOptions(
            name='memorycapacity',
            options={'ordering': ['number_of_gigabite'], 'verbose_name': 'Memory Capacity', 'verbose_name_plural': 'Memory Capacities'},
        ),
        migrations.AlterModelOptions(
            name='memoryslot',
            options={'ordering': ['number_of_slots'], 'verbose_name': 'Memory Slot', 'verbose_name_plural': 'Memory Slots'},
        ),
        migrations.AlterModelOptions(
            name='memorytype',
            options={'ordering': ['name'], 'verbose_name': 'Memory Type', 'verbose_name_plural': 'Memory Types'},
        ),
        migrations.AlterModelOptions(
            name='operationsystem',
            options={'ordering': ['name'], 'verbose_name': 'Operation System', 'verbose_name_plural': 'Operation Systems'},
        ),
        migrations.AlterModelOptions(
            name='processortype',
            options={'ordering': ['name'], 'verbose_name': 'Processor Type', 'verbose_name_plural': 'Processor Types'},
        ),
        migrations.AlterModelOptions(
            name='productbrand',
            options={'ordering': ['name'], 'verbose_name': 'Product Brand', 'verbose_name_plural': 'Product Brands'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name'], 'verbose_name': 'Product Type', 'verbose_name_plural': 'Product Types'},
        ),
        migrations.AlterModelOptions(
            name='screendiagonal',
            options={'ordering': ['name'], 'verbose_name': 'Screen Diagonal', 'verbose_name_plural': 'Screen diagonals'},
        ),
        migrations.AlterModelOptions(
            name='screenfrequency',
            options={'ordering': ['frequency_number'], 'verbose_name': 'Screen Frequency', 'verbose_name_plural': 'Screen Frequencies'},
        ),
        migrations.AlterModelOptions(
            name='screentype',
            options={'ordering': ['name'], 'verbose_name': 'Screen Type', 'verbose_name_plural': 'Screen Types'},
        ),
        migrations.AlterModelOptions(
            name='videocard',
            options={'ordering': ['video_card'], 'verbose_name': 'Video Card', 'verbose_name_plural': 'Video Cards'},
        ),
        migrations.AlterModelOptions(
            name='videocardmemory',
            options={'ordering': ['video_card_capacity'], 'verbose_name': 'Video Card Memory', 'verbose_name_plural': 'Video Card Memories'},
        ),
    ]
