# Generated by Django 3.2.8 on 2021-10-25 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0002_auto_20211025_1833'),
        ('store', '0002_characteristics_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristics',
            name='processor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.processor', verbose_name='Processor'),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='random_access_memory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.randomaccessmemory', verbose_name='RandomAccessMemory'),
        ),
    ]
