# Generated by Django 3.2.8 on 2021-10-25 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0003_battery_colorcorp_corp_datastoragedevices_videocard'),
        ('store', '0003_auto_20211025_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristics',
            name='corpus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.corp', verbose_name='Corp'),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='data_storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.datastoragedevices', verbose_name='DataStorageDevices'),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='video_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.videocard', verbose_name='VideoCard'),
        ),
    ]
