# Generated by Django 3.2.8 on 2021-10-26 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0005_auto_20211026_0900'),
        ('store', '0006_auto_20211026_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristics',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='characteristics',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='characteristics',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='characteristics',
            name='random_access_memory',
        ),
        migrations.RemoveField(
            model_name='characteristics',
            name='screen',
        ),
        migrations.AddField(
            model_name='characteristics',
            name='battery',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='camera',
            field=models.CharField(max_length=255, null=True, verbose_name='camera'),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='color',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='corp_material',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='depth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='diagonal_screen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.screendiagonal', verbose_name='ScreenDiagonal'),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='input_output',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='manipulators',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='memory_capacity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.memorycapacity', verbose_name='MemoryCapacity'),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='memory_slots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.memoryslot', verbose_name='MemorySlot'),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='memory_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.memorytype', verbose_name='NemoryType'),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='network_adapters',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='operation_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.operationsystem', verbose_name='OperationSystem'),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='processor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.processortype', verbose_name='ProcessorType'),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='screen_frequency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.screenfrequency', verbose_name='ScreenFrequency'),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='screen_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.screentype', verbose_name='ScreenType'),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='video_card_memory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.videocardmemory', verbose_name='VideoCardMemory'),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='width',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='wireless_connection',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
