# Generated by Django 3.2.8 on 2021-10-26 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0008_auto_20211026_2011'),
        ('store', '0007_auto_20211026_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristics',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.productbrand', verbose_name='ProductBrand'),
        ),
    ]
