# Generated by Django 3.2.8 on 2021-10-27 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0008_auto_20211026_2011'),
        ('store', '0008_characteristics_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.productbrand', verbose_name='Brand of product'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='data_storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.datastoragedevices', verbose_name='Hard drive capacity'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='diagonal_screen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.screendiagonal', verbose_name='Screen diagonal'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='memory_capacity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.memorycapacity', verbose_name='Memory capacity'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='memory_slots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.memoryslot', verbose_name='Memory slots'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='memory_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.memorytype', verbose_name='Nemory type'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='operation_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.operationsystem', verbose_name='Operation system'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='processor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.processortype', verbose_name='Processor type'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='screen_frequency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.screenfrequency', verbose_name='Screen frequency'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='screen_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.screentype', verbose_name='Screen type'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='video_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.videocard', verbose_name='Video card'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='video_card_memory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.videocardmemory', verbose_name='Video card memory'),
        ),
    ]
