# Generated by Django 3.2.8 on 2021-10-27 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0008_auto_20211026_2011'),
        ('store', '0010_product_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristics',
            name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristics.productbrand', verbose_name='Brand of product'),
        ),
    ]
