# Generated by Django 3.2.8 on 2021-10-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20211027_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=models.FileField(upload_to='photos/Data%y/%m/%d/', verbose_name='images'),
        ),
    ]
