# Generated by Django 3.2.8 on 2021-10-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_productimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='camera',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='camera'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='depth',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='width',
            field=models.FloatField(null=True),
        ),
    ]
