# Generated by Django 3.2.8 on 2021-10-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20211027_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='only_name',
            field=models.CharField(max_length=255, null=True, verbose_name='only_name'),
        ),
    ]
