# Generated by Django 3.2.8 on 2021-11-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20211101_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Total price'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='total_price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Total price'),
        ),
    ]
