# Generated by Django 3.2.8 on 2021-11-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20211102_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=100, verbose_name='coupon')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='discount')),
            ],
        ),
    ]
