# Generated by Django 3.2.8 on 2021-11-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_userorderhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorderhistory',
            name='user',
        ),
        migrations.AddField(
            model_name='userorderhistory',
            name='ip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
