# Generated by Django 4.0.6 on 2022-09-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_productcomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_keys',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
