# Generated by Django 4.0.6 on 2022-09-20 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0033_alter_cartproduct_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.IntegerField()),
                ('place', models.CharField(max_length=50, verbose_name='place')),
                ('ware_house_id', models.IntegerField()),
                ('ware_house_name', models.CharField(max_length=50, verbose_name='ware_house')),
                ('delivery_type', models.CharField(max_length=50, verbose_name='delivery_type')),
                ('price_method', models.IntegerField()),
                ('reciever_first_name', models.CharField(max_length=50, verbose_name='reciever_first_name')),
                ('reciever_last_name', models.CharField(max_length=50, verbose_name='reciever_last_name')),
                ('reciever_middle_name', models.CharField(max_length=50, verbose_name='reciever_middle_name')),
                ('reciever_phone', models.CharField(max_length=50, verbose_name='reciever_phone')),
                ('total_price', models.FloatField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart', verbose_name='cart')),
                ('coupones', models.ManyToManyField(to='store.coupon', verbose_name='coupones')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
