# Generated by Django 4.0.6 on 2022-09-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_order_coupones_alter_order_delivery_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupones',
            field=models.ManyToManyField(blank=True, null=True, to='store.coupon', verbose_name='coupones'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='delivery_type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='place'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_method',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='reciever_first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='reciever_first_name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reciever_last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='reciever_last_name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reciever_middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='reciever_middle_name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reciever_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='reciever_phone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ware_house_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ware_house_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ware_house'),
        ),
    ]
