# Generated by Django 4.0.6 on 2022-09-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_order_coupones_alter_order_delivery_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupones',
            field=models.ManyToManyField(blank=True, to='store.coupon', verbose_name='coupones'),
        ),
    ]
