# Generated by Django 4.0.6 on 2022-09-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_order_coupones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='place_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
